# Inspired by psalm :D
# https://raw.githubusercontent.com/vimeo/psalm/5.x/.github/workflows/build-phar.yml
name: Build beanstalk-cli PHAR

on:
  push:
    branches:
      - main
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  build-phar:
    permissions:
      contents: write # for release
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none
        env:
          fail-fast: true

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for composer to automatically detect root package version

      - name: Get Composer Cache Directories
        id: composer-cache
        run: |
          echo "files_cache=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
          echo "vcs_cache=$(composer config cache-vcs-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.composer-cache.outputs.files_cache }}
            ${{ steps.composer-cache.outputs.vcs_cache }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Run composer install
        run: composer install --optimize-autoloader

      # This can probably be optimized by not requiring it globally
      # But for now this is okay
      - name: Build the phar
        run: |
          composer global require humbug/box
          $(composer global  config --quiet --global --absolute bin-dir)/box compile --no-parallel

      - name: Upload release assets
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/beanstalk-cli.phar
          file_glob: true
          tag: ${{ github.ref }}
